1. Pythonの行列オブジェクト

- Pythonには数学の行列を表すオブジェクトは存在しない。

- データサイエンス分野（ディープラーニング）では、行列演算が多く使用される。

- NumPy（Numerical Python）は、Pythonで数値計算（Numerical Computing）を迅速かつ便利に行うための代表的なライブラリである。

- 外部ライブラリとして pip install numpy コマンドで別途インストールする必要があります。（Anaconda には含まれています）

2. NumPyの行列演算

\# 行列の積

前列の列数 = 後列の行数
            ↑
       そうであれば、うまくいく可能性がある
       

結果サイズ =
(前の行列の行数) × (後の行列の列数)

2×3 @ 3×4 → 2×4

In [7]:
import numpy as np

# 一般リストの演算と比較
print([[1, 2],[3, 4]] + [[5, 6],[7, 8]])

print([[1, 2],[3, 4]] * [[5, 6],[7, 8]]) 
# can't multiply sequence by non-int of type 'list'

[[1, 2], [3, 4], [5, 6], [7, 8]]


TypeError: can't multiply sequence by non-int of type 'list'

In [14]:
a = np.array([[1, 2],
              [3, 4]])
print(a)

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
# [1+5  2+6] 
# [3+7  4+8]

[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]


In [ ]:
c = np.array([[5, 6],
              [7, 8]])
d = np.array([[1, 2],
              [3, 4]])
print(c - d)

[[4 4]
 [4 4]]


In [10]:
e = np.array([[1, 2],
              [3, 4]])
print(e * 10)

[[10 20]
 [30 40]]


\# 行列積 (Matrix Multiplication) 

- 重要：行列積演算は行列のサイズを縮小できる。 
- データサイエンスでは、入力値の特性（特徴、変数）が多すぎる場合に圧縮する際に行列積演算を使用する。

In [19]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]]) # 2行3列

b = np.array([[10],
              [20],
              [30]]) # 3列1列

print(a @ b) # 結果は2行1列
# [1×10 + 2×20 + 3×30]
# [4×10 + 5×20 + 6×30]

[[140]
 [320]]


In [21]:
# 前置行列

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]
